apps/simple_page/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, url
from .views import HomePage
from .views import MakeOrder

urlpatterns = patterns('',
    url(r'^$', HomePage.as_view(), name='home_page'),
    url(r'^make-order/$', MakeOrder.as_view(), name='order_make'),
)

restrukt_book/urls.py
# -*- coding: utf-8 -*-

from django.conf import settings
from django.contrib import admin
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^', include('apps.simple_page.urls')),
    url(r'^djangojs/', include('djangojs.urls')),
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^pay2pay/', include('pay2pay.urls')),
    url(r'^robots\.txt$', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')),
    url(r'^sitemap\.xml', TemplateView.as_view(template_name='sitemao.xml', content_type='text/xml')),
)

if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^admin/', include(admin.site.urls)),
        url(r'^media/(.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
        url(r'^static/(.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT, 'show_indexes': True}),
    )
else:
    urlpatterns += patterns('',
        url(r'^admin/', include('admin_honeypot.urls')),
        url(r'^admin.php', include('admin_honeypot.urls')),
        url(r'^admin-secret/', include(admin.site.urls)),
    )

apps/simple_page/models.py
# -*- coding: utf-8 -*-

from django.db import models
from pay2pay.models import Payment


class Order(models.Model):
    name = models.CharField('ФИО', max_length=128)
    address = models.CharField('Адрес', max_length=246)
    email = models.EmailField('Email')
    payment = models.ForeignKey(Payment, verbose_name='Платеж', blank=True, null=True)
    sent = models.BooleanField('Отправлен')
    created = models.DateTimeField('Создан', auto_now_add=True)

    def __unicode__(self):
        return self.name

    class Meta:
        ordering = ('created',)
        verbose_name = 'Заказ'
        verbose_name_plural = 'заказы'


class Video(models.Model):
    name = models.CharField('Название', max_length=128)
    code = models.CharField('Код видео', max_length=16)
    show = models.BooleanField('Показывать', default=True)

    def __unicode__(self):
        return self.name

    class Meta:
        ordering = ('show',)
        verbose_name = 'Видео'
        verbose_name_plural = 'Видео'

apps/simple_page/forms.py
# -*- coding: utf-8 -*-

from django import forms
from .models import Order


class OrderForm(forms.ModelForm):
    class Meta:
        exclude = ('sent', 'payment', 'created')
        model = Order

apps/simple_page/views.py
# -*- coding: utf-8 -*-

import json
from django.http import HttpResponse
from django.views.generic import TemplateView, FormView
from .forms import OrderForm
from constance import config
from pay2pay.models import Payment
from .models import Video


class HomePage(TemplateView):
    template_name = 'simple_page/home_page.html'

    def get_context_data(self, **kwargs):
        ctx = super(HomePage, self).get_context_data(**kwargs)
        ctx['videos'] = Video.objects.filter(show=True)
        return ctx


class MakeOrder(FormView):
    form_class = OrderForm

    def form_invalid(self, form):
        errors = {}
        for name in form.fields:
            error = form.errors.get(name)
            if error:
                errors[name] = error[0]
        return HttpResponse(json.dumps(errors), status=200, mimetype='application/json')

    def form_valid(self, form):
        payment = Payment(
            amount=config.SHOP_ORDER_AMOUNT,
            description=config.SHOP_ORDER_DESCIPTION
        )
        payment.save()

        order = form.save()
        order.payment = payment
        order.save()

        pay_data = {
            'xml': payment.xml.encode('base64'),
            'sign': payment.signature,
        }

        return HttpResponse(json.dumps(pay_data), status=201, mimetype='application/json')

templates/base.html
<!DOCTYPE html>
<html lang="ru">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <title>{% block title %}{% endblock %} &mdash; {{ config.SITE_TITLE }}</title>
        <meta name="keywords" content="{{ conf.SITE_KEYWORDS }}">
        <meta name="description" content="{{ conf.SITE_DESCRIPTION }}">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="shortcut icon" href="{{ STATIC_URL }}favicon.ico" type="image/x-icon" />
        <link rel="icon" href="{{ STATIC_URL }}favicon.ico" type="image/x-icon" />
        <link href='http://fonts.googleapis.com/css?family=Open+Sans&subset=latin,cyrillic' rel='stylesheet' type='text/css'>
        <link href='http://fonts.googleapis.com/css?family=PT+Sans+Caption&subset=latin,cyrillic' rel='stylesheet' type='text/css'>
        <link href='http://fonts.googleapis.com/css?family=Roboto:400,700&subset=latin,cyrillic' rel='stylesheet' type='text/css'>

        {% load compress %}
        {% compress css %}
            {% if debug %}
                <link href="{{ STATIC_URL }}vendors/bootstrap/css/bootstrap.css" rel="stylesheet" media="screen">
            {% else %}
                <link href="{{ STATIC_URL }}vendors/bootstrap/css/bootstrap.min.css" rel="stylesheet" media="screen">
            {% endif %}
            <link href="{{ STATIC_URL }}css/style.css" rel="stylesheet" media="screen">
            {% block extra_css %}
            {% endblock %}
        {% endcompress %}
    </head>
    <body class="{% block class %}{% endblock %}">
        {% include "includes/menu.html" %}

        <div class="container" id="content">
            <div class="content-wrapper">
                {% block content %}
                {% endblock %}
            </div>
        </div>

        <div class="row-fluid" id="footer">
            <div class="container">
                <div class="row">

                </div>
            </div>
        </div>
    </body>

    {% if debug %}
        <script src="{{ STATIC_URL }}vendors/jquery.js" type="text/javascript"></script>
    {% else %}
        <script src="{{ STATIC_URL }}vendors/jquery.min.js" type="text/javascript"></script>
    {% endif %}

    {% compress js %}
        {% if debug %}
            <script src="{{ STATIC_URL }}vendors/bootstrap/js/bootstrap.js" type="text/javascript"></script>
        {% else %}
            <script src="{{ STATIC_URL }}vendors/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
        {% endif %}
        <script src="{{ STATIC_URL }}scripts/utils.js" type="text/javascript"></script>
        {% block extra_js %}
        {% endblock %}
    {% endcompress %}

    {% load js %}
    {% django_js i18n=false jquery=false %}

    {% include "includes/metrika.html" %}
</html>

templates/includes/menu.html
<div class="navbar">
    <div class="navbar-inner navbar-fixed-top" id="menu">
        <div class="container">
            {% ifnotequal request.path '/' %}
                {% url 'home_page' as home_page_url %}
            {% endifnotequal %}
            <ul class="nav pull-left">
                <li>
                    <a href="{{ home_page_url }}#content" id="logo">
                        <img src="{{ STATIC_URL }}img/logo.jpg" />
                    </a>
                </li>
                <li>
                    <a href="{{ home_page_url }}#buy">
                        <i class="icon-shopping-cart"></i>
                        Купить
                    </a>
                </li>
                <li>
                    <a href="{{ home_page_url }}#video">
                        Видео
                    </a>
                </li>
                <li>
                    <a href="{{ home_page_url }}#author">
                        От автора
                    </a>
                </li>
            </ul>
        </div>
    </div>
</div>

templates/includes/metrika.html
{% if not debug %}
    <!-- Yandex.Metrika counter -->
    <script type="text/javascript">
    (function (d, w, c) {
        (w[c] = w[c] || []).push(function() {
            try {
                w.yaCounter21656464 = new Ya.Metrika({id:21656464,
                        webvisor:true,
                        clickmap:true,
                        trackLinks:true,
                        accurateTrackBounce:true});
            } catch(e) { }
        });

        var n = d.getElementsByTagName("script")[0],
            s = d.createElement("script"),
            f = function () { n.parentNode.insertBefore(s, n); };
        s.type = "text/javascript";
        s.async = true;
        s.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//mc.yandex.ru/metrika/watch.js";

        if (w.opera == "[object Opera]") {
            d.addEventListener("DOMContentLoaded", f, false);
        } else { f(); }
    })(document, window, "yandex_metrika_callbacks");
    </script>
    <noscript><div><img src="//mc.yandex.ru/watch/21656464" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
    <!-- /Yandex.Metrika counter -->
{% endif %}

templates/pay2pay/payment_fail.html
{% extends "base.html" %}

{% block title %}{{ config.ORDER_FAIL_TITLE }}{% endblock %}

{% block extra_js %}
    <script type="text/javascript" src="{{ STATIC_URL }}scripts/set-content-height.js"></script>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="span12">
            <h1>{{ config.ORDER_FAIL_TITLE }}</h1>
            <p>
                {{ config.ORDER_FAIL_TEXT|linebreaksbr|safe }}
            </p>
        </div>
    </div>
{% endblock %}

templates/pay2pay/payment_success.html
{% extends "base.html" %}

{% block title %}{{ config.ORDER_SUCCESS_TITLE }}{% endblock %}

{% block extra_js %}
    <script type="text/javascript" src="{{ STATIC_URL }}scripts/set-content-height.js"></script>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="span12">
            <h1>{{ config.ORDER_SUCCESS_TITLE }}</h1>
            <p>
                {{ config.ORDER_SUCCESS_TEXT|linebreaksbr|safe }}
            </p>
        </div>
    </div>
{% endblock %}

templates/simple_page/home_page.html
{% extends "base.html" %}

{% block title %}Главная{% endblock %}

{% block extra_css %}
    <link href="{{ STATIC_URL }}vendors/fancybox/jquery.fancybox.css" rel="stylesheet" media="screen">
{% endblock %}

{% block extra_js %}
    <script type="text/javascript" src="{{ STATIC_URL }}scripts/order-form.js"></script>
    {% if debug %}
        <script src="{{ STATIC_URL }}vendors/fancybox/jquery.fancybox.js"></script>
    {% else %}
        <script src="{{ STATIC_URL }}vendors/fancybox/jquery.fancybox.pack.js"></script>
    {% endif %}
    <script type="text/javascript" src="{{ STATIC_URL }}js/youtube-player.js"></script>
{% endblock %}

{% block class %}home{% endblock %}

{% block content %}
    <script src="http://www.youtube.com/player_api"></script>
    <div class="row" id="about">
        <div class="span12 text">
            <h1>Книга Реструкт</h1>
            {{ config.HOME_RECENSION|safe }}
        </div>
    </div>

    <div class="row buy-row" id="buy">
        <div class="span4">
                <span class="price">
                    Книга <ins>650</ins> <img src="{{ STATIC_URL }}img/ruble.gif" class="ruble-img" />
                </span>
                <img src="{{ STATIC_URL }}img/book-cover.jpg" alt="Книга Реструкт Максима Тесака">
                <span class="price">+</span>
                <span class="price">
                    доставка <ins>200</ins> <img src="{{ STATIC_URL }}img/ruble.gif" class="ruble-img" />
                </span>
                <img src="{{ STATIC_URL }}img/ru_ems.jpg" alt="Досxтавка Почтой Роиссе">
        </div>
        <div class="span8">
            <form id="order_form" class="form-actions">
                {% csrf_token %}
                <div class="control-group">
                    <label class="control-label" for="id_address">Адрес доставки</label>
                    <div class="controls">
                        <input type="text" maxlength="256" id="id_address" name="address" placeholder="город, улица, дом, квартира, индекс" />
                        <span class="help-inline"></span>
                    </div>
                </div>

                <div class="control-group">
                    <label class="control-label" for="id_name">ФИО</label>
                    <div class="controls">
                        <input type="text" maxlength="256" id="id_name" name="name" placeholder="ФИО полностью" />
                        <span class="help-inline"></span>
                    </div>
                </div>

                <div class="control-group">
                    <label class="control-label" for="id_email">Email</label>
                    <div class="controls">
                        <input type="text" maxlength="256" id="id_email" name="email" placeholder="Для уведомлений" />
                        <span class="help-inline"></span>
                    </div>
                </div>

                <ul class="thumbnails pay-systems">
                    <li>
                        <img src="{{ STATIC_URL }}img/ps_qiwilk_32.png" alt="QiWi кошелек">
                    </li>
                    <li>
                        <img src="{{ STATIC_URL }}img/ps_bank_32.png" alt="Visa & MasterCard">
                    </li>
                    <li>
                        <img src="{{ STATIC_URL }}img/ps_ac_32.png" alt="Альфаклик">
                    </li>
                    <li>
                        <img src="{{ STATIC_URL }}img/ps_wmr_32.png" alt="WebMoney WMR">
                    </li>
                    <li>
                        <img src="{{ STATIC_URL }}img/ps_wmz_32.png" alt="WebMoney WMZ">
                    </li>
                </ul>
                <button type="submit" class="btn btn-large btn-success">
                    <i class="icon-shopping-cart icon-white"></i> Купить
                </button>
                <img id="loader" src="{{ STATIC_URL }}img/loader.gif" />
            </form>
            <div class="row-fluid">
                Есть вопросы? Задаем &mdash; <a href="http://vk.com/id171878219" title="Поддержка">Неллюшечка Егорычева</a>
                {% if config.SITE_PHONE %}{{ config.SITE_PHONE }}{% endif %}
            </div>

            <form id="payment_form" action="https://merchant.pay2pay.com/?page=init" method="POST">
                <input type="hidden" id="id_xml" name="xml" value="" />
                <input type="hidden" id="id_sign" name="sign" value="" />
                <input type="submit" id="payment_form_submit" value="" />
            </form>
        </div>
    </div>

    <div class="row" id="video">
        <div class="span12">
            <h2>Видео</h2>
        </div>
        <ul class="thumbnails">
            <noindex>
                {% for video in videos %}
                    <li class="span3">
                        <div class="thumbnail">
                            <a class="thumbnail fancybox fancybox.iframe" rel="nofollow" href="http://www.youtube.com/embed/{{ video.code }}?enablejsapi=1&wmode=opaque">
                                <img src="http://img.youtube.com/vi/{{ video.code }}/hqdefault.jpg" alt="{{ video.name }}">
                            </a>
                        </div>
                    </li>
                {% endfor %}
            </noindex>
        </ul>
    </div>

    <div class="row" id="author">
        <div class="span9 text">
            <h2>От автора</h2>
            <p>
                Здравствуйте, мои маленькие любители экстремизма!
            </p>
            <p>
                Я примерно знаю, что вы ожидаете увидеть в этой книге. И уверен, что это вы увидите. Но спешу вас заверить, в ней на самом деле ничего этого нет. Вся книга придумана от начала и до конца. Любые совпадения с реальными людьми и событиями или случайны или являются плодом вашего воспаленного экстремизмом разума. Автор не согласен ни с одним написанным в книге словом. Мало того, он, на всякий случай глубоко её осуждает. Извиняется перед всеми, кого она непременно оскорбит. Не советует читать книгу никому. Особенно — агрессивно настроенным группам граждан, в том числе несовершеннолетних.
            </p>
            <p>
                Надеюсь, что вы не свихнетесь от ее прочтения так, как автор свихнулся для ее написания. Жизнь ради Идеи — глупость. Жить надо ради удовольствия. Для того, чтобы заработать побольше денег, купить машину, квартиру, дачу. Жениться и вырастить сына. Твердо усвойте это перед тем, как читать дальше.
            </p>
        </div>
        <div class="span3">
            <img class="img-polaroid" src="{{ STATIC_URL }}img/author.jpg">
        </div>
    </div>
{% endblock %}

templates/simple_page/order_fail.html
{% extends "base.html" %}

{% block title %}{{ config.ORDER_FAIL_TITLE }}{% endblock %}

{% block extra_js %}
    <script type="text/javascript" src="{{ STATIC_URL }}scripts/set-content-height.js"></script>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="span12">
            <h1>{{ config.ORDER_FAIL_TITLE }}</h1>
            <p>
                {{ config.ORDER_FAIL_TEXT|linebreaksbr|safe }}
            </p>
        </div>
    </div>
{% endblock %}

templates/simple_page/order_success.html
{% extends "base.html" %}

{% block title %}{{ config.ORDER_SUCCESS_TITLE }}{% endblock %}

{% block extra_js %}
    <script type="text/javascript" src="{{ STATIC_URL }}scripts/set-content-height.js"></script>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="span12">
            <h1>{{ config.ORDER_SUCCESS_TITLE }}</h1>
            <p>
                {{ config.ORDER_SUCCESS_TEXT|linebreaksbr|safe }}
            </p>
        </div>
    </div>
{% endblock %}